# Generated by Django 3.0.3 on 2020-02-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0006_auto_20200209_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='cooking.CustomUser')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='cooking.CustomUser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='cooking.Relationship', to='cooking.CustomUser'),
        ),
    ]
