# Generated by Django 3.0.3 on 2020-02-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0008_auto_20200214_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_1',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language_2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language_3',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
