# Generated by Django 3.0.3 on 2020-02-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0009_auto_20200216_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language_3',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
