# Generated by Django 3.0.3 on 2020-02-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=128)),
                ('cost', models.CharField(max_length=128)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking.Cuisine')),
            ],
        ),
    ]
