# Generated by Django 3.0.3 on 2020-02-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0012_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(choices=[('M', 'Money'), ('P', 'Product'), ('C', 'Help with cooking'), ('D', 'Help with wash dish')], default='M', max_length=1),
        ),
    ]
