# Generated by Django 3.0.3 on 2020-02-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0014_auto_20200227_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
